volumes:
    postgres-data:
    pgadmin-data:
    kafka-data:
    grafana-data:
    spark-checkpoints:

networks:
    supply_chain:
        driver: bridge

services:
    kafka1:
        image: confluentinc/cp-kafka:7.7.0
        container_name: kafka1
        hostname: kafka1
        ports:
            - "127.0.0.1:9092:9092"
        healthcheck:
            test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka1:29092 --list > /dev/null 2>&1"]
            interval: 15s
            timeout: 15s
            retries: 10
            start_period: 45s
        environment:
            CLUSTER_ID: bgVKLUurTM6-Wx0gyGaPxQ
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29092,EXTERNAL://127.0.0.1:9092"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
            KAFKA_DEFAULT_REPLICATION_FACTOR: 2
            KAFKA_MIN_INSYNC_REPLICAS: 1

        networks:
            - supply_chain

    kafka2:
        image: confluentinc/cp-kafka:7.7.0
        container_name: kafka2
        hostname: kafka2
        ports:
            - "127.0.0.1:9093:9093"
        healthcheck:
            test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka2:29092 --list > /dev/null 2>&1"]
            interval: 15s
            timeout: 15s
            retries: 10
            start_period: 45s
        environment:
            CLUSTER_ID: bgVKLUurTM6-Wx0gyGaPxQ
            KAFKA_NODE_ID: 2
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:29093"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:29092,EXTERNAL://127.0.0.1:9093"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
            KAFKA_DEFAULT_REPLICATION_FACTOR: 2
            KAFKA_MIN_INSYNC_REPLICAS: 1

        networks:
            - supply_chain

    schema-registry:
        image: confluentinc/cp-schema-registry:latest
        container_name: schema-registry
        ports:
            - "127.0.0.1:8082:8082"

        depends_on:
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
        
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka1:29092,PLAINTEXT://kafka2:29092"
            SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8082"
        networks:
        - supply_chain

    #kafdrop for UI 
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop
        ports:
            - "127.0.0.1:9020:9000"

        environment:
            KAFKA_BROKERCONNECT: "kafka1:29092,kafka2:29092"
            JVM_OPTS: "-Xms32M -Xmx128M"

        depends_on:
            - kafka1
            - kafka2

        networks:
            - supply_chain

    kafka-producer:
        build:
            context: .
            dockerfile: kafka/Dockerfile

        command:
            -   python
            - -m
            - kafka.streaming
        environment:
            KAFKA_BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29092"
        depends_on:
            kafka2:
                condition: service_healthy
            kafka1:
                condition: service_healthy
        networks:
            - supply_chain

        restart: "no"

    #Spark master services 
    spark-master:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-master
        hostname: spark-master
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master

        ports:
            - "127.0.0.1:9090:8080"
            - "127.0.0.1:7077:7077"
        
        environment:
            AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
            AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        volumes:
            - ./spark:/spark
        networks:
            - supply_chain

        restart: unless-stopped

    spark-worker1:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker1
        hostname: spark-worker1
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9100:8081"
        volumes:
            - ./spark:/spark

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077
        networks:
            - supply_chain      

        restart: unless-stopped


    spark-worker2:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker2
        hostname: spark-worker2
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9095:8081"

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077

        volumes:
            - ./spark:/spark    
        networks:
            - supply_chain
        restart: unless-stopped

    spark-worker3:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker3
        hostname: spark-worker3
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9097:8081"

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077

        volumes:
            - ./spark:/spark    
        networks:
            - supply_chain
        restart: unless-stopped
    spark-worker4:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker4
        hostname: spark-worker4
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9098:8081"

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077

        volumes:
            - ./spark:/spark    
        networks:
            - supply_chain
        restart: unless-stopped

    spark-worker5:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker5
        hostname: spark-worker5
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9099:8081"

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077

        volumes:
            - ./spark:/spark    
        networks:
            - supply_chain
        restart: unless-stopped

    spark-worker6:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-worker6
        hostname: spark-worker6
        command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077

        ports:
            - "127.0.0.1:9101:8081"

        depends_on:
            - spark-master

        environment:
            - SPARK_WORKER_MEMORY=4g
            - SPARK_WORKER_CORES=2
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077

        volumes:
            - ./spark:/spark    
        networks:
            - supply_chain
        restart: unless-stopped

    #SPARK VALIDATION JOB
    spark-validation:
        build:
            context: ./spark
            dockerfile: Dockerfile
        container_name: spark-validation
        environment:
            AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
            AWS_SECRET_KEY: ${AWS_SECRET_KEY}

        entrypoint: ["/bin/bash", "-c"]

        command:
            - |
                sleep 15
                /opt/spark/bin/spark-submit \
                  --master spark://spark-master:7077 \
                  --deploy-mode client \
                  --executor-cores 1 \
                  --executor-memory 1500m \
                  --conf spark.executor.memoryOverhead=512m \
                  --conf spark.sql.shuffle.partitions=2 \
                  --conf spark.default.parallelism=2 \
                  --conf spark.network.timeout=600s \
                  --conf spark.cores.max=2 \
                  --conf spark.driver.extraClassPath=/opt/spark/jars/* \
                  --conf spark.executor.extraClassPath=/opt/spark/jars/* \
                  /spark/validation_job.py
        depends_on:
            spark-master:
                condition: service_started
            spark-worker1:
                condition: service_started
            spark-worker2:
                condition: service_started
            spark-worker3:
                condition: service_started
            spark-worker4:
                condition: service_started
            spark-worker5:
                condition: service_started
            spark-worker6:
                condition: service_started
        networks:
            - supply_chain
        restart: unless-stopped

    #state processing Job
    spark-state-processing-job:
        build:
            context: ./spark
            dockerfile: Dockerfile
        container_name: spark-state-processing

        entrypoint: ["/bin/bash", "-c"]
        command:
            - |
                sleep 20
                /opt/spark/bin/spark-submit \
                    --master spark://spark-master:7077 \
                    --deploy-mode client \
                    --executor-cores 1 \
                    --executor-memory 1500m \
                    --conf spark.executor.memoryOverhead=512m \
                    --conf spark.sql.shuffle.partitions=2 \
                    --conf spark.default.parallelism=2 \
                    --conf spark.network.timeout=600s \
                    --conf spark.cores.max=2 \
                    --conf spark.driver.extraClassPath=/opt/spark/jars/* \
                    --conf spark.executor.extraClassPath=/opt/spark/jars/* \
                    /spark/state_processing_job.py

        depends_on:
            spark-worker6:
                condition: service_started
            spark-worker5:
                condition: service_started
            spark-worker4:
                condition: service_started
            spark-worker3:
                condition: service_started
            spark-worker2:
                condition: service_started
            spark-worker1:
                condition: service_started
            spark-master:
                condition: service_started
            spark-validation:
                condition: service_started
            redis:
                condition: service_started
            dynamodb-local:
                condition: service_started
            kafka1:
                condition: service_started
            kafka2:
                condition: service_started

        environment:
            KAFKA_BROKER: kafka1:29092,kafka2:29092
            INPUT_TOPIC: scan_events_validated
            OUTPUT_TOPIC: state-processed-data

            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0

            DYNAMODB_TABLE: package-tracking-state
            DYNAMODB_ENDPOINT: http://dynamodb-local:8000
            AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
            AWS_SECRET_KEY: ${AWS_SECRET_KEY}
            AWS_REGION: ${AWS_REGION}

            CHECKPOINT_LOCATION: /spark/checkpoints/state_processing

        volumes:
            -   spark-checkpoints:/spark/checkpoints
        networks:
            - supply_chain
        restart: unless-stopped
    spark-eta-calculator-job:
        build:
            context: ./spark
            dockerfile: Dockerfile
        container_name: spark-eta-calculator

        entrypoint: ["/bin/bash", "-c"]

        command:
            - |
                sleep 30
                /opt/spark/bin/spark-submit \
                    --master spark://spark-master:7077 \
                    --deploy-mode client \
                    --executor-cores 1 \
                    --executor-memory 1500m \
                    --conf spark.executor.memoryOverhead=512m \
                    --conf spark.sql.shuffle.partitions=2 \
                    --conf spark.default.parallelism=2 \
                    --conf spark.network.timeout=600s \
                    --conf spark.cores.max=2 \
                    --conf spark.driver.extraClassPath=/opt/spark/jars/* \
                    --conf spark.executor.extraClassPath=/opt/spark/jars/* \
                    /spark/eta_calculator_job.py

        depends_on:
            spark-master:
                condition: service_started

            spark-worker1:
                condition: service_started

            spark-worker2:
                condition: service_started

            spark-state-processing-job:
                condition: service_started

            spark-worker3:
                condition: service_started

            spark-worker4:
                condition: service_started

            spark-worker5:
                condition: service_started

            spark-worker6:
                condition: service_started

            redis:
                condition: service_started

            kafka1:
                condition: service_healthy

            kafka2:
                condition: service_healthy

        environment:
            KAFKA_BROKER: kafka1:29092,kafka2:29092

            INPUT_TOPIC: state-processed-data
            OUTPUT_TOPIC: eta-calculated-data

            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_PASSWORD: ${REDIS_PASSWORD}

            CHECKPOINT_LOCATION: /spark/checkpoints/eta_calculator

            AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
            AWS_SECRET_KEY: ${AWS_SECRET_KEY}
            AWS_REGION: ${AWS_REGION}

        volumes:
            -   spark-checkpoints:/spark/checkpoints

        networks:
            - supply_chain

        restart: unless-stopped

    spark-delay-detector:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-delay-detector

        entrypoint: ["/bin/bash", "-c"]

        command:
            - |
                sleep 40
                /opt/spark/bin/spark-submit \
                  --master spark://spark-master:7077 \
                  --deploy-mode client \
                  --executor-cores 1 \
                  --executor-memory 1500m \
                  --conf spark.executor.memoryOverhead=512m \
                  --conf spark.sql.shuffle.partitions=2 \
                  --conf spark.default.parallelism=2 \
                  --conf spark.network.timeout=600s \
                  --conf spark.cores.max=2 \
                  --conf spark.driver.extraClassPath=/opt/spark/jars/* \
                  --conf spark.executor.extraClassPath=/opt/spark/jars/* \
                  /spark/delay_detector_job.py

        depends_on:
            spark-master:
                condition: service_started

            spark-worker1:
                condition: service_started
            spark-worker2:
                condition: service_started
            spark-worker3:
                condition: service_started

            spark-worker4:
                condition: service_started
            spark-worker5:
                condition: service_started
            spark-worker6:
                condition: service_started
            spark-state-processing-job:
                condition: service_started
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
        environment:
            KAFKA_BROKERS: kafka1:29092,kafka2:29092

            INPUT_TOPIC: state-processed-data
            OUTPUT_TOPIC: delay-notifications
            DLQ_TOPIC: delay-detector-dlq

            CHECKPOINT_LOCATION: /spark/checkpoints/delay_detector

            DELAY_THRESHOLD_MINUTES: 15
            TRIGGER_INTERVAL: "30 seconds"

            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_PASSWORD: ${REDIS_PASSWORD}

        volumes:
            -   spark-checkpoints:/spark/checkpoints
        networks:
            - supply_chain
        restart: unless-stopped
    #spark analytics aggregator
    spark-analytics-aggregator:
        build:
            context: ./spark
            dockerfile: Dockerfile

        container_name: spark-analytics-aggregator

        entrypoint: ["/bin/bash", "-c"]


        command:
            - |
                sleep 40
                /opt/spark/bin/spark-submit \
                  --master spark://spark-master:7077 \
                  --deploy-mode client \
                  --executor-cores 1 \
                  --executor-memory 1500m \
                  --conf spark.executor.memoryOverhead=512m \
                  --conf spark.sql.shuffle.partitions=2 \
                  --conf spark.default.parallelism=2 \
                  --conf spark.network.timeout=600s \
                  --conf spark.cores.max=2 \
                  --conf spark.driver.extraClassPath=/opt/spark/jars/* \
                  --conf spark.executor.extraClassPath=/opt/spark/jars/* \
                  /spark/analytics_aggregator.py

        depends_on:
            spark-state-processing-job:
                condition: service_started
            spark-master:
                condition: service_started
            spark-worker1:
                condition: service_started
            spark-worker2:
                condition: service_started

            spark-worker3:
                condition: service_started
            spark-worker5:
                condition: service_started
            spark-worker6:
                condition: service_started
            spark-worker4:
                condition: service_started
            kafka2:
                condition: service_healthy
            kafka1:
                condition: service_healthy

        volumes:
            -   spark-checkpoints:/spark/checkpoints
        networks:
            - supply_chain
        restart: unless-stopped
    #prometheus service for monitoring

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "127.0.0.1:9096:9090"

        volumes:
            - ./monitoring/prometheus:/etc/prometheus

        depends_on:
            - spark-master
            - spark-worker1
            - spark-worker2
        networks:
            - supply_chain

    #grafana service for monitoring
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "127.0.0.1:3000:3000"

        volumes:
            - grafana-data:/var/lib/grafana
            - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
            - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

        networks:
            - supply_chain

    #alertmanager service for monitoring
    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        ports:
            - "127.0.0.1:9094:9093"
        networks:
            - supply_chain

    kafka-exporters:
        image: danielqsj/kafka-exporter:latest
        container_name: kafka-exporters
        ports:
            - "127.0.0.1:9308:9308"
        
        command:
            - '--kafka.server=kafka1:29092'
            - '--kafka.server=kafka2:29092'
            - '--web.listen-address=:9308'
            - '--log.level=info'
        
        depends_on:
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
        networks:
            - supply_chain
    # cadvisor service for monitoring docker containers 
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        container_name: cadvisor
        ports:
            - "8083:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        privileged: true
        devices:
            - /dev/kmsg
        networks:
            - supply_chain

    postgres:
        image: postgres:16
        restart: on-failure
        container_name: postgres
        env_file:
            - .env
        environment:
        - POSTGRES_DB=${POSTGRES_SCHEMA}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "${HOST_PORT}:5432"

        volumes:
            - ./:/bootcamp/
            - ./data.dump:/docker-entrypoint-initdb.d/data.dump
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - postgres-data:/var/lib/postgresql/data

        networks:
            - supply_chain

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: on-failure
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - supply_chain

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            - supply_chain

    dynamodb-local:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb-local
        ports:
            - "127.0.0.1:8000:8000"
        command: ["-jar", "DynamoDBLocal.jar", "-inMemory"]
        networks:
            - supply_chain


