name: supply-chain-workflow

on:
    push:
        branches:
            - main
jobs:
    production-environment:
        runs-on: ubuntu-latest
        environment: production
        env:
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
            DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
            DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
            HOST_PORT: ${{ secrets.HOST_PORT }}
            PGADMIN_EMAIL: ${{ secrets.PDADMIN_EMAIL }}
            PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD}}
            PGADMIN_PORT: ${{ secrets.PGADMIN_PORT }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            POSTGRESS_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

        steps:
            - name: Inspect the values inside the job 
              run: |
                echo "Env secrets (masked):    $AWS_SECRET_KEY"
                echo " ENC secrets (masked): $AWS_ACCESS_KEY"
    
    intergration-test:
        name: Integration Test
        runs-on: ubuntu-latest

        environment:
            name: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create CI environment file 
              env: 
                 AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
                 AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                 CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
                 DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
                 DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
                 HOST_PORT: ${{ secrets.HOST_PORT }}
                 PGADMIN_EMAIL: ${{ secrets.PDADMIN_EMAIL }}
                 PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD}}
                 PGADMIN_PORT: ${{ secrets.PGADMIN_PORT }}
                 POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                 POSTGRESS_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                 POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
                 POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                 REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
              run: |
                cat > .env <<EOF
                 AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
                AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
                DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
                DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
                HOST_PORT: ${{ secrets.HOST_PORT }}
                PGADMIN_EMAIL: ${{ secrets.PDADMIN_EMAIL }}
                PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD}}
                PGADMIN_PORT: ${{ secrets.PGADMIN_PORT }}
                POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                POSTGRESS_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

            - name: create docker network
              run: docker network create supply_chain

            - name: start Dcoker compose 
              run: docker compose up -d

            - name: check running containers
              run: docker ps
            
            - name: Wait for services 
              run: sleep 30
              
            - name: Run test to test
              run: pytest test/ -v -x

            - name: Show logs 
              if: failure()
              run: |
                docker compose logs --no-color